DROP TABLE scores;

CREATE TABLE games (
    id SERIAL PRIMARY KEY,
    played_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    scoreboard_id INT NOT NULL REFERENCES scoreboards(id) ON DELETE CASCADE
);

CREATE TABLE scores (
    id SERIAL PRIMARY KEY,
    score INT NOT NULL,
    game_id INT NOT NULL REFERENCES games(id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
